---
# tasks file for web
- name: Instal Nginx
  apt:
   name: nginx
   state: present

- name: index.html is present
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0555
  notify:
    - restart nginx

